---
- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python2.7
    - mongodb
    - git
    - virtualenv
    - redis-server
    - redis-tools
- name: add user for cve_tracker service
  user:
    name: cve_tracker
    home: /srv/cve_tracker
- name: clone cve_tracker service
  git:
    repo: https://github.com/lineageos/cve_tracker
    dest: /srv/cve_tracker/app
    update: yes
- name: Install cve_tracker config
  template:
    src: files/cve_tracker.app.cfg.j2
    dest: /srv/cve_tracker/app/app.cfg
    owner: cve_tracker
    group: cve_tracker
    mode: 0600
- name: install pip requirements
  pip:
    requirements: /srv/cve_tracker/app/requirements.txt
    virtualenv: /srv/cve_tracker/venv
  become: yes
  become_user: cve_tracker
- name: install extra pip modules
  pip:
    name: "{{item}}"
    virtualenv: /srv/cve_tracker/venv
  become: yes
  become_user: cve_tracker
  with_items:
    - gunicorn
    - redis
- name: install systemd unit file
  copy:
    src: files/cve_tracker.systemd.unit
    dest: /etc/systemd/system/cve_tracker.service
- name: install nginx config
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/cve_tracker
    owner: root
    group: root
    mode: 0644
- name: restart nginx
  systemd:
    state: restarted
    name: nginx
- name: restart cve_tracker
  systemd:
    state: restarted
    name: cve_tracker
    daemon_reload: yes
- name: check http status
  shell: "curl --fail -I -H 'Host: cve.lineageos.org' https://localhost/ -k"
  args:
    warn: false
